export const getUser = async(req, res) => {
try{
  
} catch(err){
    console.log(err);
}
}